# Peceptron and Decision Tree combined
## Mohammad Sulaiman Behzad

### The method proposed and applied below:
We can use percx

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [2]:
X_train = pd.read_csv('train.csv', header=None, skiprows=[0])
X_test = pd.read_csv('test.csv', header=None, skiprows=[0])
Y_train = pd.read_csv('train_labels.csv',header=None, skiprows=[0])
Y_test = pd.read_csv('test_labels.csv', header=None, skiprows=[0])

In [3]:
X_train.shape

(800, 11)

In [4]:
X_test.shape

(91, 11)

In [5]:
X_train.describe()

0           1           4           5           6  \
count  800.000000  800.000000  640.000000  800.000000  800.000000   
mean   447.867500    2.311250   29.632031    0.541250    0.387500   
std    258.858126    0.835312   14.617948    1.139044    0.811275   
min      1.000000    1.000000    0.670000    0.000000    0.000000   
25%    224.750000    2.000000   20.000000    0.000000    0.000000   
50%    449.500000    3.000000   28.000000    0.000000    0.000000   
75%    677.250000    3.000000   38.000000    1.000000    0.000000   
max    891.000000    3.000000   80.000000    8.000000    6.000000   

                  7           8  
count  5.890000e+02  800.000000  
mean   2.649668e+05   32.592395  
std    4.819212e+05   50.726982  
min    6.950000e+02    0.000000  
25%    2.416000e+04    7.925000  
50%    2.361710e+05   14.500000  
75%    3.477430e+05   31.275000  
max    3.101298e+06  512.329200

In [6]:
print(X_train.isnull().sum())

0       0
1       0
2       0
3       0
4     160
5       0
6       0
7     211
8       0
9     617
10      0
dtype: int64


In [7]:
X_test

0   1                                                  2       3     4   \
0   373   3                         Beavan, Mr. William Thomas    male  19.0   
1    22   2                              Beesley, Mr. Lawrence    male  34.0   
2   714   3                         Larsson, Mr. August Viktor    male  29.0   
3   648   1                Simonius-Blumer, Col. Oberst Alfons    male  56.0   
4    59   2                       West, Miss. Constance Mirium  female   5.0   
..  ...  ..                                                ...     ...   ...   
86  316   3                    Nilsson, Miss. Helmina Josefina  female  26.0   
87  781   3                               Ayoub, Miss. Banoura  female  13.0   
88  587   2                            Jarvis, Mr. John Denzil    male  47.0   
89  424   3  Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria ...  female  28.0   
90  432   3  Thorneycroft, Mrs. Percival (Florence Kate White)  female   NaN   

    5   6         7        8    9  10  
0    0   0  323951.0   8.0500  NaN  S  
1    0   0  248698.0  13.0000  D56  S  
2    0   0    7545.0   9.4833  NaN  S  
3    0   0   13213.0  35.5000  A26  C  
4    1   2       NaN  27.7500  NaN  S  
..  ..  ..       ...      ...  ... ..  
86   0   0  347470.0   7.8542  NaN  S  
87   0   0    2687.0   7.2292  NaN  C  
88   0   0  237565.0  15.0000  NaN  S  
89   1   1  347080.0  14.4000  NaN  S  
90   1   0  376564.0  16.1000  NaN  S  

[91 rows x 11 columns]

In [8]:
X_train = X_train.drop([9], axis=1)
X_test = X_test.drop([9], axis=1)
# X_train.head()

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(X_train[0])
X_train[0] = le.transform(X_train[0])
le.fit(X_test[0])
X_test[0] = le.transform(X_test[0])
le.fit(X_train[2])
X_train[2] = le.transform(X_train[2])
le.fit(X_test[2])
X_test[2] = le.transform(X_test[2])
# le.fit(X_train[9])
# X_train[9] = le.transform(X_train[9])
# le.fit(X_test[9])
# X_test[9] = le.transform(X_test[9])

In [10]:
le.fit(X_train[3])

LabelEncoder()

In [11]:
le.classes_

array(['female', 'male'], dtype=object)

In [12]:
x_tr_3 = le.transform(X_train[3])

In [13]:
x_tr_3

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,

In [14]:
X_train[3] = x_tr_3
print(X_train)

      0   1    2   3     4   5   6         7        8  10
0    430   3  741   0  63.0   0   0    4134.0   9.5875  S
1    246   1   28   0  63.0   1   0   13502.0  77.9583  S
2    198   3  276   1  51.0   0   0   21440.0   8.0500  S
3    561   3  446   1  51.0   0   0  347743.0   7.0542  S
4     23   3   39   0  38.0   1   5  347077.0  31.3875  S
..   ...  ..  ...  ..   ...  ..  ..       ...      ... ..
795   15   2  322   0  55.0   0   0  248706.0  16.0000  S
796  587   1  153   1  47.0   0   0    5727.0  25.5875  S
797  727   3    9   1  26.0   0   0    3474.0   7.8875  S
798  377   3  630   1  18.0   1   1  370129.0  20.2125  S
799  141   1  778   1  51.0   0   1       NaN  61.3792  C

[800 rows x 10 columns]


In [15]:
le.fit(X_test[3])

LabelEncoder()

In [16]:
x_te_3 = le.transform(X_test[3])
X_test[3] = x_te_3
X_test.head()

0   1   2   3     4   5   6         7        8  10
0  40   3  10   1  19.0   0   0  323951.0   8.0500  S
1   0   2  11   1  34.0   0   0  248698.0  13.0000  S
2  77   3  44   1  29.0   0   0    7545.0   9.4833  S
3  73   1  72   1  56.0   0   0   13213.0  35.5000  C
4   4   2  85   0   5.0   1   2       NaN  27.7500  S

In [17]:
le.fit(X_train[10])
le.classes_

array(['C', 'Q', 'S'], dtype=object)

In [18]:
x_tr_10 = le.transform(X_train[10])
x_tr_10

array([2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0,
       0, 1, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 2, 0, 0,
       2, 1, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 0, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 0, 0, 0, 2,
       0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 2, 1, 1, 2,
       2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,

In [19]:
X_train[10] = x_tr_10
X_train.head()

0   1    2   3     4   5   6         7        8   10
0  430   3  741   0  63.0   0   0    4134.0   9.5875   2
1  246   1   28   0  63.0   1   0   13502.0  77.9583   2
2  198   3  276   1  51.0   0   0   21440.0   8.0500   2
3  561   3  446   1  51.0   0   0  347743.0   7.0542   2
4   23   3   39   0  38.0   1   5  347077.0  31.3875   2

In [20]:
le.fit(X_test[10])

LabelEncoder()

In [21]:
x_te_10 = le.transform(X_test[10])
X_test[10] = x_te_10
X_test.head()

0   1   2   3     4   5   6         7        8   10
0  40   3  10   1  19.0   0   0  323951.0   8.0500   2
1   0   2  11   1  34.0   0   0  248698.0  13.0000   2
2  77   3  44   1  29.0   0   0    7545.0   9.4833   2
3  73   1  72   1  56.0   0   0   13213.0  35.5000   0
4   4   2  85   0   5.0   1   2       NaN  27.7500   2

## Handle null values

In [22]:
from numpy import nan
X_train.fillna(X_train.mean(), inplace=True)
X_test.fillna(X_test.mean(), inplace=True)

In [23]:
print(X_train.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
10    0
dtype: int64


In [24]:
print(X_test.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
10    0
dtype: int64


In [25]:
X_train.head()

0   1    2   3     4   5   6         7        8   10
0  430   3  741   0  63.0   0   0    4134.0   9.5875   2
1  246   1   28   0  63.0   1   0   13502.0  77.9583   2
2  198   3  276   1  51.0   0   0   21440.0   8.0500   2
3  561   3  446   1  51.0   0   0  347743.0   7.0542   2
4   23   3   39   0  38.0   1   5  347077.0  31.3875   2

In [26]:
# imp_features = [0, 1, 2, 3, 4, 5, 6, 8,10]
# X_train_imp = X_train[imp_features]
# # 3 > 1 > 4 > 5 > 8 > 2 > 7 > 0 > 10
# # 0 not bad, 10 bad, 8 very bad, 3 good, 5 bad, 6 bad
# # 0, 4, 5, 6, 10 entropy min bad
# # 1, 2, 3, 4, 7, 8 entropy max
# # [1, 2, 3, 4, 7] gini good
# X_train_imp.head()

In [27]:
# X_test_imp = X_test[imp_features]
# X_test_imp.head()

In [28]:
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [29]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [30]:
ppn = Perceptron(max_iter=50, eta0=0.001,random_state=1)

ppn.fit(X_train_std, Y_train.values.ravel())

Perceptron(eta0=0.001, max_iter=50, random_state=1)

In [31]:
ppn.coef_

array([[ 0.0025223 , -0.00337959,  0.00257426, -0.00305586, -0.00261657,
        -0.00194254, -0.001588  , -0.0063383 ,  0.00467755,  0.00094328]])

In [32]:
y_predict_train = ppn.predict(X_train_std)
y_predict_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [33]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_train, y_predict_train))
print('Mean Squared Error:', metrics.mean_squared_error(Y_train, y_predict_train))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_train, y_predict_train)))
print('Accuracy: ', metrics.accuracy_score(Y_train, y_predict_train.round()))

Mean Absolute Error: 0.2775
Mean Squared Error: 0.2775
Root Mean Squared Error: 0.5267826876426369
Accuracy:  0.7225


In [34]:
y_predict = ppn.predict(X_test_std)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [35]:
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, y_predict))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, y_predict))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, y_predict)))
print('Accuracy: ', metrics.accuracy_score(Y_test, y_predict.round()))

Mean Absolute Error: 0.32967032967032966
Mean Squared Error: 0.32967032967032966
Root Mean Squared Error: 0.5741692517632145
Accuracy:  0.6703296703296703


In [36]:
classifier = DecisionTreeClassifier(class_weight=ppn.class_weight,criterion="entropy",max_depth=20,min_samples_split=5, min_samples_leaf=3, random_state=1, splitter='best')
# classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=20, min_samples_leaf=3,
                       min_samples_split=5, random_state=1)

In [37]:
y_predict_train_DT = classifier.predict(X_train)
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_train, y_predict_train_DT))
print('Mean Squared Error:', metrics.mean_squared_error(Y_train, y_predict_train_DT))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_train, y_predict_train_DT)))
print('Accuracy: ', metrics.accuracy_score(Y_train, y_predict_train_DT.round()))

Mean Absolute Error: 0.065
Mean Squared Error: 0.065
Root Mean Squared Error: 0.25495097567963926
Accuracy:  0.935


In [38]:
importance = classifier.feature_importances_
for i,v in enumerate(importance):
    print('Feature: %0d, Score: %.3f' % (i,v))
print(importance)

Feature: 0, Score: 0.073
Feature: 1, Score: 0.095
Feature: 2, Score: 0.111
Feature: 3, Score: 0.280
Feature: 4, Score: 0.129
Feature: 5, Score: 0.026
Feature: 6, Score: 0.012
Feature: 7, Score: 0.125
Feature: 8, Score: 0.142
Feature: 9, Score: 0.008
[0.07312007 0.09514708 0.11055111 0.27971965 0.12921822 0.02592922
 0.0117022  0.12536423 0.14163656 0.00761165]
